// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RunningAnalytics.Infrastructure.Data;

#nullable disable

namespace RunningAnalytics.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826182022_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RunningAnalytics.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b7d3a1c-0e5f-4c63-9e91-1a2b3c4d5e6f"),
                            CreatedAt = new DateTime(2026, 8, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "testuser1@example.com",
                            Name = "TestUser 1",
                            PasswordHash = "TEST_ONLY_HASH_1"
                        },
                        new
                        {
                            Id = new Guid("9c8e4b2d-1f60-5d74-af02-2b3c4d5e6f70"),
                            CreatedAt = new DateTime(2026, 8, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "testuser2@example.com",
                            Name = "TestUser 2",
                            PasswordHash = "TEST_ONLY_HASH_2"
                        },
                        new
                        {
                            Id = new Guid("ad9f5c3e-2071-6e85-b013-3c4d5e6f7081"),
                            CreatedAt = new DateTime(2026, 8, 3, 10, 15, 0, 0, DateTimeKind.Utc),
                            Email = "testuser3@example.com",
                            Name = "TestUser 3",
                            PasswordHash = "TEST_ONLY_HASH_3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
